# Generated by Django 6.0.4 on 2026-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stack_description',
            field=models.TextField(blank=True),
        ),
    ]
